// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDThh-snWkqF828KtEMvZ6EkyFLv4FBYD4',
    appId: '1:622547032514:web:a5eaa76eec01fc3aaade5b',
    messagingSenderId: '622547032514',
    projectId: 'flutterweatherapptest',
    authDomain: 'flutterweatherapptest.firebaseapp.com',
    storageBucket: 'flutterweatherapptest.appspot.com',
    measurementId: 'G-ZY6ELYBYT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA10MjMFspfsASdxY4OaAPseJDECaA1W0U',
    appId: '1:622547032514:android:f3e08e4e276edf94aade5b',
    messagingSenderId: '622547032514',
    projectId: 'flutterweatherapptest',
    storageBucket: 'flutterweatherapptest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnRQxpoWRzbuYPT_cm2730BTZY5LwvU_4',
    appId: '1:622547032514:ios:d5d3ccb560136a88aade5b',
    messagingSenderId: '622547032514',
    projectId: 'flutterweatherapptest',
    storageBucket: 'flutterweatherapptest.appspot.com',
    iosBundleId: 'com.example.weatherAppTest01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnRQxpoWRzbuYPT_cm2730BTZY5LwvU_4',
    appId: '1:622547032514:ios:8a26e326f9e69a14aade5b',
    messagingSenderId: '622547032514',
    projectId: 'flutterweatherapptest',
    storageBucket: 'flutterweatherapptest.appspot.com',
    iosBundleId: 'com.example.weatherAppTest01.RunnerTests',
  );
}
